### ISSUE TITLE
[REQUEST] Auto message on certain time

### ISSUE THREAD

**Issue by lvp11** [RageYT/simple-announcements#4]
Hey,

It's possible to send a message on a hour?
Like, 16h the resource will send a message called "abc".

Thanks!

(Sorry for my bad english, i'm brazilian).

**Comment by RageYT** [comment]
If I remember correctly, you can convert hours to minutes and in the **config.lua** file set the **config.delay** option to the minutes converted from the hours given. For example, you want 16h every announcement so put 960 in for the config.
